### PR TITLE
feat: Add filter by ecosystem

### PR DESCRIPTION
**Pull request by romkaspb**
Good day @kunalnagar,
thank you for your work.

While in our project we have monorepository, we need the feature to run action for different ecosystems.
I made some changes and it works like a charm.

I know that it's not ready-to-merge PR, but maybe we can prepare it together? I'm not a JS developer btw :)

### CODE REVIEW

**Comment by romkaspb** [comment]
I tried to add ecosystem filter looking into PR with manifest filter - FYI

**Review by kunalnagar — APPROVED** [review]
@romkaspb - thanks for the contribution! It looks great 🚀 

1. Do you mind posting some sample results as screenshots in the comment before you merge the PR?
2. Do you mind updating the PR title to remove the `WIP` before you merge?

**Comment by romkaspb** [comment]
Hey @kunalnagar,
1. I can but there are no changes in output. We can change text to something like `You have ${alertCount} vulnerabilities in *${repoName}* for ${ecosystem} ecosystem`. What do you think?
2. Yep I will. And I will squash commits when we will be going to merge it.

**Comment by kunalnagar** [comment]
> 1. We can change text to something like

I think let's keep the existing text as I see this getting longer as more fields are added. This gave me an idea for a feature -- customize what columns/fields should be shown in the alert that gets sent out. Ecosystem could be one of those fields.

> And I will squash commits

Thanks. You can go ahead and merge.

**Comment by romkaspb** [comment]
@kunalnagar did squash and changed PR title. I don't have permissions to merge PR.

**Pull request merged**
